service: product-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: 'dev'

plugins:
  - serverless-webpack
  - serverless-s3-deploy

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
    excludeFiles: 'src/**/*.test.js'

  assets:
    targets:
      - bucket: music-store-backend-static-data-rs-scool-aws
        files:
          - source: ./swagger/
            globs:
              - '**/*.*'

functions:
  getProductsList:
    handler: src/handlers/getProductsList/getProductsList.handler
    environment: ${file(.env.json)}
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: src/handlers/getProductsById/getProductsById.handler
    environment: ${file(.env.json)}
    events:
      - http:
          path: /products/{id}
          method: get
          cors: true
  createProduct:
    handler: src/handlers/createProduct/createProduct.handler
    environment: ${file(.env.json)}
    events:
      - http:
          path: /products
          method: post
          cors: true
          request:
            schemas:
              application/json: ${file(swagger/product-schema.json)}

